# # //user
# GET http://localhost:3000/users/5ff6287847af0d3359c05317

GET    http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmY2YjM5ZWFjZmE4NzYxMDA2YjAwZDkiLCJpYXQiOjE2MTAwMDMzNTh9.N5aPL7cGAo4OzdskX03ma-N2wM-Mg_K_tOtvr0NhnOU
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmY2OTJmNDQ0ODNhMjUyNTE1YzIzNjYiLCJpYXQiOjE2MTAwMDMxMzN9.NDtOTfQRM-FMNbWxgrVO1v3y_gT6lwbcekS0KYvlfRQ
# {
#     "name": "Demarly Lewis",
#     "email": "dlewis@gmail.com",
#     "password": "12345898",
#     "age":25
# }

###

# //task
# GET http://localhost:3000/tasks/5ff51b3f1eec06217ad94cb0

# POST   http://localhost:3000/tasks
# content-type: application/json

# {
#     "description": "Reply to all messages",
#     "completed": true
# }