
POST http://localhost:3000/users/logout/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmY2YjM5ZWFjZmE4NzYxMDA2YjAwZDkiLCJpYXQiOjE2MTAxNDg5NDJ9.lIjz7w2hW5XLECXufvwRf2m2etyr_kJ_lg9VX-mNaXE